// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for ngspice shared library.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NgspiceDartBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NgspiceDartBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NgspiceDartBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ngspice initialization,
  /// printfcn: pointer to callback function for reading printf, fprintf
  /// statfcn: pointer to callback function for the status string and percent value
  /// ControlledExit: pointer to callback function for setting a 'quit' signal in caller
  /// SendData: pointer to callback function for returning data values of all current output vectors
  /// SendInitData: pointer to callback function for returning information of all output vectors just initialized
  /// BGThreadRunning: pointer to callback function indicating if workrt thread is running
  /// userData: pointer to user-defined data, will not be modified, but
  /// handed over back to caller during Callback, e.g. address of calling object
  int ngSpice_Init(
    ffi.Pointer<SendChar> printfcn,
    ffi.Pointer<SendStat> statfcn,
    ffi.Pointer<ControlledExit> ngexit,
    ffi.Pointer<SendData> sdata,
    ffi.Pointer<SendInitData> sinitdata,
    ffi.Pointer<BGThreadRunning> bgtrun,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return _ngSpice_Init(
      printfcn,
      statfcn,
      ngexit,
      sdata,
      sinitdata,
      bgtrun,
      userData,
    );
  }

  late final _ngSpice_InitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<SendChar>,
            ffi.Pointer<SendStat>,
            ffi.Pointer<ControlledExit>,
            ffi.Pointer<SendData>,
            ffi.Pointer<SendInitData>,
            ffi.Pointer<BGThreadRunning>,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('ngSpice_Init');
  late final _ngSpice_Init = _ngSpice_InitPtr
      .asFunction<
        int Function(
          ffi.Pointer<SendChar>,
          ffi.Pointer<SendStat>,
          ffi.Pointer<ControlledExit>,
          ffi.Pointer<SendData>,
          ffi.Pointer<SendInitData>,
          ffi.Pointer<BGThreadRunning>,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// initialization of synchronizing functions
  /// vsrcdat: pointer to callback function for retrieving a voltage source value from caller
  /// isrcdat: pointer to callback function for retrieving a current source value from caller
  /// syncdat: pointer to callback function for synchronization
  /// ident: pointer to integer unique to this shared library (defaults to 0)
  /// userData: pointer to user-defined data, will not be modified, but
  /// handed over back to caller during Callback, e.g. address of calling object.
  /// If NULL is sent here, userdata info from ngSpice_Init() will be kept, otherwise
  /// userdata will be overridden by new value from here.
  int ngSpice_Init_Sync(
    ffi.Pointer<GetVSRCData> vsrcdat,
    ffi.Pointer<GetISRCData> isrcdat,
    ffi.Pointer<GetSyncData> syncdat,
    ffi.Pointer<ffi.Int> ident,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return _ngSpice_Init_Sync(vsrcdat, isrcdat, syncdat, ident, userData);
  }

  late final _ngSpice_Init_SyncPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GetVSRCData>,
            ffi.Pointer<GetISRCData>,
            ffi.Pointer<GetSyncData>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('ngSpice_Init_Sync');
  late final _ngSpice_Init_Sync = _ngSpice_Init_SyncPtr
      .asFunction<
        int Function(
          ffi.Pointer<GetVSRCData>,
          ffi.Pointer<GetISRCData>,
          ffi.Pointer<GetSyncData>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// Caller may send ngspice commands to ngspice.dll.
  /// Commands are executed immediately
  int ngSpice_Command(ffi.Pointer<ffi.Char> command) {
    return _ngSpice_Command(command);
  }

  late final _ngSpice_CommandPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'ngSpice_Command',
      );
  late final _ngSpice_Command = _ngSpice_CommandPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// get info about a vector
  pvector_info ngGet_Vec_Info(ffi.Pointer<ffi.Char> vecname) {
    return _ngGet_Vec_Info(vecname);
  }

  late final _ngGet_Vec_InfoPtr =
      _lookup<ffi.NativeFunction<pvector_info Function(ffi.Pointer<ffi.Char>)>>(
        'ngGet_Vec_Info',
      );
  late final _ngGet_Vec_Info = _ngGet_Vec_InfoPtr
      .asFunction<pvector_info Function(ffi.Pointer<ffi.Char>)>();

  /// send a circuit to ngspice.dll
  /// The circuit description is a dynamic array
  /// of char*. Each char* corresponds to a single circuit
  /// line. The last-but-one entry of the array has to be a .end card,
  /// followed by the last entry NULL.
  int ngSpice_Circ(ffi.Pointer<ffi.Pointer<ffi.Char>> circarray) {
    return _ngSpice_Circ(circarray);
  }

  late final _ngSpice_CircPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>
      >('ngSpice_Circ');
  late final _ngSpice_Circ = _ngSpice_CircPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// return to the caller a pointer to the name of the current plot
  ffi.Pointer<ffi.Char> ngSpice_CurPlot() {
    return _ngSpice_CurPlot();
  }

  late final _ngSpice_CurPlotPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'ngSpice_CurPlot',
      );
  late final _ngSpice_CurPlot = _ngSpice_CurPlotPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// return to the caller a pointer to an array of all plots created
  /// so far by ngspice.dll
  ffi.Pointer<ffi.Pointer<ffi.Char>> ngSpice_AllPlots() {
    return _ngSpice_AllPlots();
  }

  late final _ngSpice_AllPlotsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Pointer<ffi.Char>> Function()>
      >('ngSpice_AllPlots');
  late final _ngSpice_AllPlots = _ngSpice_AllPlotsPtr
      .asFunction<ffi.Pointer<ffi.Pointer<ffi.Char>> Function()>();

  /// return to the caller a pointer to an array of vector names in the plot
  /// named by plotname
  ffi.Pointer<ffi.Pointer<ffi.Char>> ngSpice_AllVecs(
    ffi.Pointer<ffi.Char> plotname,
  ) {
    return _ngSpice_AllVecs(plotname);
  }

  late final _ngSpice_AllVecsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<ffi.Char>)
        >
      >('ngSpice_AllVecs');
  late final _ngSpice_AllVecs = _ngSpice_AllVecsPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<ffi.Char>)
      >();

  /// returns TRUE if ngspice is running in a second (background) thread
  bool ngSpice_running() {
    return _ngSpice_running();
  }

  late final _ngSpice_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('ngSpice_running');
  late final _ngSpice_running = _ngSpice_runningPtr
      .asFunction<bool Function()>();

  /// set a breakpoint in ngspice
  bool ngSpice_SetBkpt(double time) {
    return _ngSpice_SetBkpt(time);
  }

  late final _ngSpice_SetBkptPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Double)>>(
        'ngSpice_SetBkpt',
      );
  late final _ngSpice_SetBkpt = _ngSpice_SetBkptPtr
      .asFunction<bool Function(double)>();

  /// Set variable no_spinit, if reading 'spinit' is not wanted.
  int ngSpice_nospinit() {
    return _ngSpice_nospinit();
  }

  late final _ngSpice_nospinitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ngSpice_nospinit');
  late final _ngSpice_nospinit = _ngSpice_nospinitPtr
      .asFunction<int Function()>();

  /// Set variable no_spiceinit, if reading '.spiceinit' is not wanted.
  int ngSpice_nospiceinit() {
    return _ngSpice_nospiceinit();
  }

  late final _ngSpice_nospiceinitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ngSpice_nospiceinit');
  late final _ngSpice_nospiceinit = _ngSpice_nospiceinitPtr
      .asFunction<int Function()>();

  /// Locking and unlocking the realloc of output vectors during simulation. May be set
  /// during reading output vectors in the primary thread, while the simulation in the
  /// background thread is moving on.
  int ngSpice_LockRealloc() {
    return _ngSpice_LockRealloc();
  }

  late final _ngSpice_LockReallocPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ngSpice_LockRealloc');
  late final _ngSpice_LockRealloc = _ngSpice_LockReallocPtr
      .asFunction<int Function()>();

  int ngSpice_UnlockRealloc() {
    return _ngSpice_UnlockRealloc();
  }

  late final _ngSpice_UnlockReallocPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ngSpice_UnlockRealloc');
  late final _ngSpice_UnlockRealloc = _ngSpice_UnlockReallocPtr
      .asFunction<int Function()>();

  /// Reset ngspice as far as possible.
  int ngSpice_Reset() {
    return _ngSpice_Reset();
  }

  late final _ngSpice_ResetPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ngSpice_Reset');
  late final _ngSpice_Reset = _ngSpice_ResetPtr.asFunction<int Function()>();
}

/// Complex numbers.
final class ngcomplex extends ffi.Struct {
  @ffi.Double()
  external double cx_real;

  @ffi.Double()
  external double cx_imag;
}

typedef ngcomplex_t = ngcomplex;

/// vector info obtained from any vector in ngspice.dll.
/// Allows direct access to the ngspice internal vector structure,
/// as defined in include/ngspice/devc.h .
final class vector_info extends ffi.Struct {
  /// Same as so_vname.
  external ffi.Pointer<ffi.Char> v_name;

  /// Same as so_vtype.
  @ffi.Int()
  external int v_type;

  /// Flags (a combination of VF_*).
  @ffi.Short()
  external int v_flags;

  /// Real data.
  external ffi.Pointer<ffi.Double> v_realdata;

  /// Complex data.
  external ffi.Pointer<ngcomplex_t> v_compdata;

  /// Length of the vector.
  @ffi.Int()
  external int v_length;
}

typedef pvector_info = ffi.Pointer<vector_info>;

final class vecvalues extends ffi.Struct {
  /// name of a specific vector
  external ffi.Pointer<ffi.Char> name;

  /// actual data value
  @ffi.Double()
  external double creal;

  /// actual data value
  @ffi.Double()
  external double cimag;

  /// if 'name' is the scale vector
  @ffi.Bool()
  external bool is_scale;

  /// if the data are complex numbers
  @ffi.Bool()
  external bool is_complex;
}

typedef pvecvalues = ffi.Pointer<vecvalues>;

final class vecvaluesall extends ffi.Struct {
  /// number of vectors in plot
  @ffi.Int()
  external int veccount;

  /// index of actual set of vectors. i.e. the number of accepted data points
  @ffi.Int()
  external int vecindex;

  /// values of actual set of vectors, indexed from 0 to veccount - 1
  external ffi.Pointer<pvecvalues> vecsa;
}

typedef pvecvaluesall = ffi.Pointer<vecvaluesall>;

/// info for a specific vector
final class vecinfo extends ffi.Struct {
  /// number of vector, as postion in the linked list of vectors, starts with 0
  @ffi.Int()
  external int number;

  /// name of the actual vector
  external ffi.Pointer<ffi.Char> vecname;

  /// TRUE if the actual vector has real data
  @ffi.Bool()
  external bool is_real;

  /// a void pointer to struct dvec *d, the actual vector
  external ffi.Pointer<ffi.Void> pdvec;

  /// a void pointer to struct dvec *ds, the scale vector
  external ffi.Pointer<ffi.Void> pdvecscale;
}

typedef pvecinfo = ffi.Pointer<vecinfo>;

/// info for the current plot
final class vecinfoall extends ffi.Struct {
  /// the plot
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> title;

  external ffi.Pointer<ffi.Char> date;

  external ffi.Pointer<ffi.Char> type;

  @ffi.Int()
  external int veccount;

  /// the data as an array of vecinfo with length equal to the number of vectors in the plot
  external ffi.Pointer<pvecinfo> vecs;
}

typedef pvecinfoall = ffi.Pointer<vecinfoall>;

/// callback functions
/// addresses received from caller with ngSpice_Init() function
/// /
/// /* sending output from stdout, stderr to caller
typedef SendChar =
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Void>)
    >;

/// char* string to be sent to caller output
/// int   identification number of calling ngspice shared lib
/// void* return pointer received from caller, e.g. pointer to object having sent the request
/// /
/// /* sending simulation status to caller
typedef SendStat =
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Void>)
    >;

/// char* simulation status and value (in percent) to be sent to caller
/// int   identification number of calling ngspice shared lib
/// void* return pointer received from caller
/// /
/// /* asking for controlled exit
typedef ControlledExit =
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Int,
        ffi.Bool,
        ffi.Bool,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
      )
    >;

/// int   exit status
/// NG_BOOL  if true: immediate unloading dll, if false: just set flag, unload is done when function has returned
/// NG_BOOL  if true: exit upon 'quit', if false: exit due to ngspice.dll error
/// int   identification number of calling ngspice shared lib
/// void* return pointer received from caller
/// /
/// /* send back actual vector data
typedef SendData =
    ffi.NativeFunction<
      ffi.Int Function(pvecvaluesall, ffi.Int, ffi.Int, ffi.Pointer<ffi.Void>)
    >;

/// send back initailization vector data
typedef SendInitData =
    ffi.NativeFunction<
      ffi.Int Function(pvecinfoall, ffi.Int, ffi.Pointer<ffi.Void>)
    >;

/// indicate if background thread is running
typedef BGThreadRunning =
    ffi.NativeFunction<
      ffi.Int Function(ffi.Bool, ffi.Int, ffi.Pointer<ffi.Void>)
    >;

/// ask for VSRC EXTERNAL value
typedef GetVSRCData =
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ffi.Double>,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
      )
    >;

/// ask for ISRC EXTERNAL value
typedef GetISRCData =
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ffi.Double>,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
      )
    >;

/// ask for new delta time depending on synchronization requirements
typedef GetSyncData =
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Double,
        ffi.Pointer<ffi.Double>,
        ffi.Double,
        ffi.Int,
        ffi.Int,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
      )
    >;

const String NGSPICE_PACKAGE_VERSION = '46+';

const int HAS_NG_BOOL = 1;
